import Navbar from "@/components/navbar";
import SideView from "@/components/sideView";
import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata:Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col bg-zinc-900 border-2 border-green-500 h-screen rounded-lg ${inter.className}`}>
        <Navbar />
        <div className="flex flex-row flex-1">
          <SideView />
          {children}
        </div>
      </body>
    </html>
  );
}
